# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- main: main.go
  binary: ambarictl
  goos:
  - linux
  goarch:
  - amd64
  ldflags:
  - -s -X main.Version={{.Version}} -X main.GitRevString={{.Commit}}
  env:
  - CGO_ENABLED=1
- main: main.go
  binary: ambarictl
  goos:
  - darwin
  goarch:
  - amd64
  ldflags:
  - -s -X main.Version={{.Version}} -X main.GitRevString={{.Commit}}
  env:
  - CGO_ENABLED=1
  - CC=o64-clang
  - CXX=o64-clang++
archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
checksum:
  name_template: 'SHA256.txt'
snapshot:
  name_template: SNAPSHOT-{{.Commit}}
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
