name: "Print configs"
inputs:
  - name: AmbariServerConfig
    default: /etc/ambari-server/conf/ambari.properties
tasks:
  - name: "Ambari server config"
    ambari_server: true
    type: RemoteCommand
    command: "cat {{ .AmbariServerConfig }}"
  - name: "Ambari agent configs"
    type: RemoteCommand
    ambari_agent: true
    command: "cat /etc/ambari-agent/conf/ambari-agent.ini"
  - name: "Print infra-solr-env.sh script"
    type: RemoteCommand
    components: INFRA_SOLR
    command: "cat /etc/ambari-infra-solr/conf/infra-solr-env.sh"
  - name: "Print user home"
    type: LocalCommand
    command: "cat /etc/hosts"
